version: "3.7"
services:
  postgres:
    image: "postgres:12"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432
    networks:
      - default